site:
  title: Industrial Digital Twin Docs
  url: https://industrialdigitaltwin.io
  start_page: index::index.adoc 

content:
  sources:
 
    - url: .
      branches: [ HEAD ]
      start_path: .

    - url: https://github.com/admin-shell-io/aas-specifications
      branches: [ main ]
      start_path: .

    - url: https://github.com/admin-shell-io/idta-submodel-templates
      branches: [ main ]
      start_path: published/*/*/*/docs

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: .nojekyll 

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
