site:
  title: Industrial Digital Twin Docs
  url: https://industrialdigitaltwin.io
  start_page: index::index.adoc  # if using AsciiDoc for your homepage

content:
  sources:
    # 1) This umbrella repo (for your dashboard/index.adoc)
    - url: .
      branches: [ HEAD ]
      start_path: .
    # 2) AAS Specs module
    - url: https://github.com/admin-shell-io/aas-specifications
      branches: [ main ]
      start_path: .
    # 3) Submodel Templates module
    - url: https://github.com/admin-shell-io/idta-submodel-templates
      branches: [ main ]
      start_path: published/*/*/*/docs

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: .nojekyll    # preserve nested folders on GitHub Pages

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specifications/refs/heads/main/plantuml/puml-theme-idta.puml
