site:
  title: Industrial Digital Twin Docs
  url: https://industrialdigitaltwin.io
  start_page: index::index.adoc

content:
  sources:
    - url: .
      branches: [ HEAD ]
      start_path: .
    - url: https://admin-shell-io.github.io/aas-specifications
      branches: [ HEAD ]
      start_path: .
    - url: https://admin-shell-io.github.io/idta-submodel-templates
      branches: [ HEAD ]
      start_path: .

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: .nojekyll

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specifications/refs/heads/main/plantuml/puml-theme-idta.puml
