name: Build & Deploy Combined Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout umbrella repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Create redirect for AAS Specs
      - name: Generate AAS Specs redirect
        run: |
          mkdir -p build/site/aas-specs-antora
          cat > build/site/aas-specs-antora/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=https://admin-shell-io.github.io/aas-specs-antora/index/home/index.html" />
            <title>Redirecting to AAS Specs</title>
          </head>
          <body>
            <p>Redirecting to <a href="https://admin-shell-io.github.io/aas-specs-antora/index/home/index.html">AAS Specifications Documentation</a>...</p>
          </body>
          </html>
          EOF

      # 3. Create redirect for Submodel Templates
      - name: Generate Submodel Templates redirect
        run: |
          mkdir -p build/site/submodel-templates-antora
          cat > build/site/submodel-templates-antora/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=https://admin-shell-io.github.io/submodel-templates-antora/index/home/index.html" />
            <title>Redirecting to Submodel Templates</title>
          </head>
          <body>
            <p>Redirecting to <a href="https://admin-shell-io.github.io/submodel-templates-antora/index/home/index.html">Submodel Templates Documentation</a>...</p>
          </body>
          </html>
          EOF

      # 4. Assemble minimal redirect site
        # (only redirects and dashboard)
        run: |
          # build/site already has redirect index.html files from steps 2 & 3
          cp index.html build/site/index.html

      # 5. Deploy the combined site to GitHub Pages Deploy the combined site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          publish_branch: gh-pages
