name: Build & Deploy Docs Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Antora
        run: npm install --global @antora/cli @antora/site-generator-default

      - name: Build site
        run: npx antora antora-playbook.yml --to-dir=build/site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          publish_branch: gh-pages  
