jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Initialize npm & install local dev-deps
      - name: Set up Node.js and install Antora
        uses: actions/setup-node@v3
        with:
          node-version: '18'        # or whatever LTS you prefer
      - run: |
          npm ci                   # installs @antora/cli & @antora/site-generator-default
      # 2. Build the site
      - name: Build with Antora
        run: npx antora antora-playbook.yml --to-dir=build/site
      # 3. Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
