name: Build & Deploy Combined Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout umbrella repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Checkout pre-built site from AAS Specs (gh-pages branch)
      - name: Checkout AAS Specs static site
        uses: actions/checkout@v3
        with:
          repository: admin-shell-io/aas-specs-antora
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: aas-specs-antora

      # 3. Checkout pre-built site from Submodel Templates (gh-pages branch)
      - name: Checkout Submodel Templates static site
        uses: actions/checkout@v3
        with:
          repository: admin-shell-io/submodel-templates-antora
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: submodel-templates-antora

      # 4. Copy both static sites into a single build directory
      - name: Assemble combined site
        run: |
          mkdir -p build/site/aas-specs-antora
          cp -R aas-specs-antora/* build/site/aas-specs-antora/
          mkdir -p build/site/submodel-templates-antora
          cp -R submodel-templates-antora/* build/site/submodel-templates-antora/
          # Copy umbrella dashboard
          cp index.html build/site/index.html

      # 5. Deploy the combined site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          publish_branch: gh-pages
