name: Deploy Combined Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create site directory
        run: mkdir -p build/site

      - name: Copy umbrella content
        run: |
          mkdir -p build/site
          cp -v index.html build/site/
          cp -v .nojekyll build/site/
          cp -v CNAME build/site/
          ls -l build/site/

      - name: Download AAS Specifications site
        run: |
          mkdir -p build/site/aas-specifications
          wget -q -r -nH --cut-dirs=1 --no-parent --reject="index.html*" https://admin-shell-io.github.io/aas-specifications/
          cp -r aas-specifications/* build/site/aas-specifications/ || true

      - name: Download Submodel Templates site
        run: |
          mkdir -p build/site/idta-submodel-templates
          wget -q -r -nH --cut-dirs=1 --no-parent --reject="index.html*" https://admin-shell-io.github.io/idta-submodel-templates/
          cp -r idta-submodel-templates/* build/site/idta-submodel-templates/ || true

      - name: List deployed files
        run: |
          echo "Contents of build/site:"
          ls -lR build/site/
          echo "Contents of build/site/index.html:"
          cat build/site/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/site
          branch: gh-pages
          clean: true
          force: true
